image: atlassian/default-image:2

pipelines:
  branches:
    staging:
      - step:
          name: 'Build and deploy to Staging'
          deployment: staging
          script:
            - echo "Deploying to $DEPLOYMENT"
            - npm install
            - npm run build
            - rm -rf node_modules .git .vscode
            - npm install --only=production
            - zip -r medina-service-$BITBUCKET_BUILD_NUMBER.zip .
            - pipe: microsoft/azure-web-apps-deploy:1.0.2
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: 'MEDINA'
                AZURE_APP_NAME: 'stg-medina-service'
                ZIP_FILE: medina-service-$BITBUCKET_BUILD_NUMBER.zip
                DEBUG: 'true'

