version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "tennispro2020"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:
  pgdata:

networks:
  postgres-network:
    driver: bridge
