development:
  database:
    dialect: postgres
    host: localhost
    port: 5432
    username: postgres
    password: tennispro2020
    database: tp
    logger: false
    dialectOptions:
      ssl: false

  storage: 'DefaultEndpointsProtocol=https;AccountName=storagedevtennispro;AccountKey=GL2YGT3jbBNoeFw04IlWDEItn0cCi/XV6XJohtfe804QT2i7O2oG09CQ1SnMYjUWkapf6q285QoqabBUMOex/w==;EndpointSuffix=core.windows.net'
  
  auth:
    secret: teste
    
production:
  database:
    dialect: postgres
    host: db-tennispro-prod.postgres.database.azure.com
    port: 5432
    username: tennisprod@db-tennispro-prod
    password: tennispro@2020
    database: tennis
    logger: false
    dialectOptions:
      ssl:
        require: true
        ca: ./certs/BaltimoreCyberTrustRoot.crt.pem
        
  storage: 'DefaultEndpointsProtocol=https;AccountName=storagedevtennispro;AccountKey=GL2YGT3jbBNoeFw04IlWDEItn0cCi/XV6XJohtfe804QT2i7O2oG09CQ1SnMYjUWkapf6q285QoqabBUMOex/w==;EndpointSuffix=core.windows.net'

  auth:
    secret: teste

