production:
  database:
    dialect: postgres
    host: db-tennispro-prod.postgres.database.azure.com
    port: 5432
    username: tennisprod@db-tennispro-prod
    password: tennispro@2020
    database: tennis
    logger: false
    dialectOptions:
      ssl:
        require: true
        ca: ./certs/BaltimoreCyberTrustRoot.crt.pem

  auth:
    secret: teste

development:
  database:
    dialect: postgres
    host: localhost
    port: 5432
    username: postgres
    password: tennispro2020
    database: tp
    logger: true
    dialectOptions:
      ssl: false

  auth:
    secret: teste
